.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ACLHOUND" "7" "July 2014" "" ""
.
.SH "NAME"
\fBaclhound\fR \- An ACL compiler for various platforms
.
.SH "SYNOPSIS"
\fBaclhound\fR [ commands ]
.
.SH "DESCRIPTION"
ACLHound compiles generic firewall policies into platform specific configuration
.
.P
ACLHound takes as input a custom policy language and compiles a representation specific for the specified vendor which can be deployed on firewall devices\.
.
.P
ACLHound is designed to assist humans in managing hundreds of ACLs across tens of devices\. One key focus point is maximum re\-usability of ACL components such as groups of hosts, groups of ports and the policies themselves\.
.
.SH "SYNTAX"
todo: acl hound policy
.
.SH "AUTHOR"
Job Snijders \fIjob@instituut\.net\fR
.
.SH "COPYRIGHT"
ACLHound is Copyright (C) 2014 Job Snijders
