__version__     = "0.26.4"
__author__      = "Job Snijders"
__author_email__ = "job@instituut.net"
__copyright__   = "Copyright 2014, Kristian Larsson"
__license__     = "BSD 2-Clause"
__status__      = "Development"
__url__         = "https://github.com/job/aclhound"
